### ISSUE TITLE
lacking in license

### ISSUE THREAD

**Issue by EMCP** [Noba1anc3/Faster-RCNN-TensorFlow-2#3]
Hi , I just wanted to point out your project looks interesting but lacks a license file .. you don't HAVE to but it would help if I want to use this at work.. otherwise I will use the project you cited  https://github.com/Viredery/tf-eager-fasterrcnn since that one is MIT licensed 

thank you

**Comment by Noba1anc3** [comment]
Thank you for reminding me, I will add a MIT license file. Best wishes~
